#apenas simulando

name: Continuous Integration Teste

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Simulando CI
        run: echo "Running tests..." && echo "Tests passed!"

discord:
  runs-on: ubuntu-latest
  steps:

    - uses: actions/checkout@v4

    - name: Run Discord Webhook
      uses: johnnyhuy/actions-discord-git-webhook@main
      with:
        webhook_url: ${{ secrets.DISCORD_WEBHOOK }}