#apenas simulando

name: Continuous Integration Teste

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Simulando CI
        run: echo "Running tests..." && echo "Tests passed!"