#apenas simulando

name: Continuous Delivery Teste

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Simulando deploy
        run: echo "Deploying application..." && echo "Deployment completed!"