#apenas simulando

name: Continuous Integration Teste

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Simulando CI
        run: echo "Running tests..." && echo "Tests passed!"

  testes:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Upgrade pip
        run: python -m pip install --upgrade pip

      - name: Install test dependencies
        run: pip install pytest pytest-cov

      - name: Run pytest
        run: |
              pytest tests/ \
                --doctest-modules \
                --junitxml=junit/test-results.xml \
                --cov=. \
                --cov-report=xml \
                --cov-report=html
