name: Teste CI e CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build (CI)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Teste Simulando CI
        run: echo "Running tests..." && echo "Tests passed!"

  deploy:
    name: Deploy (CD)
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Teste Simulando CD
        run: echo "Deploying application..." && echo "Deployment completed!"
